server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://220.117.140.179:3306/finmodeun_db
    username: finmodeun
    password: finmodeun0904!@
  messages:
    basename: "messages/messages"
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
    - classpath*:mapper/**/*.xml

project:
  default:
    date-format: yyyy-MM-dd
  access:
    log:
      enabled: true
      filter: true
      aspect: true
  exceptions:
    item-list:
      - name: ConstraintViolationException
        status: 400
        res-code: 400
      - name: MethodArgumentNotValidException
        status: 400
        res-code: 400
      - name: InvalidValueException
        status: 400
        res-code: 400
